Return undefined when message is null
If `md5()` was passed a `null` value then an exception would get thrown:

```
TypeError: Cannot read property 'constructor' of null
  at md5 (md5.js:10:16)
  at module.exports (md5.js:154:42)
```

This commit modifies the function so that when it's passed a `null` value it has
the same behavior as when it's passed an `undefined` value which is to simply
return `undefined`.